---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ../
  require_ansible_repo: true
  ansible_verbose: true
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>
  no_proxy: localhost,127.0.0.1

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: dliappis/ubuntu-devopsci:14.04
      privileged: true
      provision_command:
        - apt-get update && apt-get install -y software-properties-common &&  add-apt-repository -y ppa:ansible/ansible
        - apt-get update && apt-get -y -q install ansible python-apt python-pycurl
      use_sudo: false
  - name: debian-7
    driver_config:
      image: dliappis/debian-devopsci:7
      privileged: true
      provision_command:
        - apt-get update && apt-get -y install python python-dev python-pip build-essential libyaml-dev python-yaml
        - pip install ansible
        - apt-get install -y -q net-tools
      use_sudo: false
  - name: debian-8
    driver_config:
      image: dliappis/debian-devopsci:8
      privileged: true
      provision_command:
        - apt-get update && apt-get -y install python python-dev python-pip build-essential libyaml-dev python-yaml curl wget
        - pip install ansible
        - apt-get install -y -q net-tools
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
      use_sudo: false
      run_command: "/sbin/init"
  - name: centos-6
    driver_config:
      image: dliappis/centos-devopsci:6
      privileged: true
      provision_command:
      use_sudo: false
  - name: centos-7
    driver_config:
      image: dliappis/centos-devopsci:7
      provision_command:
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
        - yum -y install initscripts
        - yum clean all
      run_command: "/usr/sbin/init"
      privileged: true
      use_sudo: false

suites:
  - name: standard-2x
    provisioner:
      playbook: test/integration/standard.yml
    run_list:
    attributes:
  - name: package-2x
    run_list:
    attributes:
      extra_vars:
        es_plugins:
          - plugin: lmenezes/elasticsearch-kopf
            version: master
          - plugin: license
          - plugin: marvel-agent
    provisioner:
      playbook: test/integration/package.yml
  - name: config-2x
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/config.yml
  - name: multi-2x
    run_list:
    attributes:
      extra_vars:
        es_plugins:
          - plugin: lmenezes/elasticsearch-kopf
            version: master
          - plugin: license
          - plugin: marvel-agent
    provisioner:
      playbook: test/integration/multi.yml
  - name: standard-1x
    provisioner:
      playbook: test/integration/standard.yml
    run_list:
    attributes:
      extra_vars:
        es_major_version: 1.7
        es_version: 1.7.3
  - name: package-1x
    run_list:
    attributes:
      extra_vars:
        es_major_version: 1.7
        es_version: 1.7.3
        es_plugins:
          - plugin: lmenezes/elasticsearch-kopf
            version: master
          - plugin: elasticsearch/marvel
            version: latest
    provisioner:
      playbook: test/integration/package.yml
  - name: config-1x
    run_list:
    attributes:
      extra_vars:
        es_major_version: 1.7
        es_version: 1.7.3
    provisioner:
      playbook: test/integration/config.yml
  - name: multi-1x
    run_list:
    attributes:
      extra_vars:
        es_major_version: 1.7
        es_version: 1.7.3
        es_plugins:
          - plugin: lmenezes/elasticsearch-kopf
            version: master
          - plugin: elasticsearch/marvel
            version: latest
    provisioner:
      playbook: test/integration/multi.yml
