---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ../
  require_ansible_repo: true
  ansible_verbose: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: electrical/ubuntu:14.04
      privileged: true
      provision_command:
        - echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list
        - apt-get -y -q install ansible python-apt python-pycurl ruby
      use_sudo: false
  - name: debian-7
    driver_config:
      image: electrical/debian:7.3
      privileged: true
      provision_command:
        - echo 'deb http://http.debian.net/debian/ wheezy-backports main' >> /etc/apt/sources.list
        - apt-get update
        - apt-get install -y -q ansible ruby
      use_sudo: false
  - name: debian-8
    driver_config:
      image: electrical/debian:8
      privileged: true
      provision_command: apt-get -y -q install ansible ruby
      use_sudo: false
  - name: centos-6
    driver_config:
      image: electrical/centos:6.4
      privileged: true
      use_sudo: false
  - name: centos-7
    driver_config:
      image: electrical/centos:7
      provision_command:
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - yum -y install initscripts ruby
        - BUSSER_ROOT="/tmp/verifier" GEM_HOME="/tmp/verifier/gems" GEM_PATH="/tmp/verifier/gems" GEM_CACHE="/tmp/verifier/gems/cache" gem install --no-rdoc --no-ri rake
        - chown kitchen:kitchen /tmp/verifier -R
        - yum clean all
      privileged: true
      use_sudo: false

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: default
    run_list:
    attributes:
