---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ../
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_ansible_source: false
  require_pip: true
  ansible_version: 2.4.3.0
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>
  no_proxy: localhost,127.0.0.1
  ignore_extensions_from_root: [".git",".idea",".kitchen.yml"]
  ignore_paths_from_root: [".git",".idea",".kitchen"]
  <% if ENV['VERSION'] %>
  attributes:
    extra_vars:
      es_major_version: "<%= ENV['VERSION'] %>"
      <% if ENV['VERSION'] == '5.x' %>
      es_version: '5.6.11'
      <% end %>
  <% end %>

transport:
  max_ssh_sessions: 6

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      privileged: true
      provision_command:
        - apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:ansible/ansible && add-apt-repository -y ppa:openjdk-r/ppa
        - apt-get update && apt-get -y -q install python-apt python-pycurl python-pip python-openssl build-essential libssl-dev libffi-dev python-dev locales openjdk-8-jre
        - locale-gen en_US.UTF-8 && localedef -i en_US -c -f UTF-8 en_US.UTF-8
        - pip install jmespath pyOpenSSL ndg-httpsclient cryptography==1.8.1
      use_sudo: false
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      privileged: true
      provision_command:
        - apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:ansible/ansible
        - apt-get install -y -q net-tools
        - apt-get update && apt-get -y -q install python-apt python-pycurl python-pip locales
        - locale-gen en_US.UTF-8 && localedef -i en_US -c -f UTF-8 en_US.UTF-8
        - pip install jmespath
      use_sudo: false
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
      run_command: "/sbin/init"
  - name: ubuntu-18.04
    driver_config:
      image: ubuntu:18.04
      privileged: true
      provision_command:
        - apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:ansible/ansible
        - apt-get update && apt-get -y -q install python-apt python-pycurl python-pip net-tools iproute2
        - pip install jmespath
      use_sudo: false
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
      run_command: "/sbin/init"
  - name: debian-8
    driver_config:
      image: debian:8
      privileged: true
      provision_command:
        - echo "deb http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
        - echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf
        - apt-get update && apt-get -y install -t jessie-backports openjdk-8-jre-headless
        - apt-get update && apt-get -y install python python-dev python-pip build-essential libyaml-dev python-yaml curl wget net-tools
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
        - pip install jmespath setuptools --upgrade
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
      use_sudo: false
      run_command: "/sbin/init"
  - name: debian-9
    driver_config:
      image: debian:9
      privileged: true
      provision_command:
        - apt-get update && apt-get -y install python python-dev python-pip build-essential libyaml-dev python-yaml curl wget systemd-sysv
        - apt-get install -y -q net-tools
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
        - pip install jmespath
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
      use_sudo: false
      run_command: "/sbin/init"
  - name: centos-7
    driver_config:
      image: centos:7
      provision_command:
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
        - yum -y install epel-release
        - yum -y install initscripts python-pip
        - yum clean all
        - pip install jmespath
      volume: 
        - <%=ENV['ES_XPACK_LICENSE_FILE']%>:/tmp/license.json
        - /etc # This fixes certain java file actions that check the mount point. Without this adding users fails for some docker storage drivers
      run_command: "/usr/sbin/init"
      privileged: true
      use_sudo: false

suites:
  - name: oss
    provisioner:
      idempotency_test: true
      playbook: test/integration/oss.yml
  - name: oss-upgrade
    provisioner:
      playbook: test/integration/oss-upgrade.yml
      idempotency_test: false
  - name: oss-to-xpack-upgrade
    provisioner:
      playbook: test/integration/oss-to-xpack-upgrade.yml
      idempotency_test: false
  - name: xpack
    provisioner:
      playbook: test/integration/xpack.yml
      idempotency_test: true
  - name: xpack-upgrade
    provisioner:
      playbook: test/integration/xpack-upgrade.yml
      idempotency_test: false
  - name: multi
    provisioner:
      playbook: test/integration/multi.yml
      idempotency_test: true
  - name: issue-test
    provisioner:
      playbook: test/integration/issue-test.yml
      idempotency_test: false
