---
- name: create the keystore if it doesn't exist yet
  include: elasticsearch-create-keystore.yml

- name: Manage Keystore Values
  become: yes
  become_user: "{{ es_user}}"
  elasticsearch_keystore_value:
    setting: "{{ item.setting }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default(omit) }}"
    allow_override: "{{ item.allow_override | default(omit) }}"
    configuration_path: "{{ conf_dir }}"
  with_list: "{{ es_keystore_values }}"
  no_log: True
